#cloud-config
package_upgrade: true
packages:
  - nginx
  - git
runcmd:
- systemctl enable nginx.service
- git clone "https://github.com/Ananyojha/ananyojha.github.io.git" 
- 'cp -r ./ananyojha.github.io/* /var/www/html/'
- systemctl restart nginx
